<a href="https://colab.research.google.com/github/makaita04/test-project/blob/main/Lab_4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports
- Import numpy module with the alias np on the code cell below

In [4]:
import numpy as np

# Question 1

In [5]:
a2 = np.array([[9,8,7],
              [6,5,4],
              [3,2,1],
              [11,12,13],
              [14,15,16]])


a3 = np.array([[[1,2,3,4],
                [5,6,7,8],
                [10,11,12,13]],

              [[15,16,17,18],
              [19,20,21,22],
              [23,24,25,26]]])

a) Run the code cell above and find the length of arrays `a2` and `a3`

In [8]:
len(a2)


5

In [9]:
len(a3)

2

b) Find the shape of arrays `a2` and `a3`

In [10]:
a2.shape

(5, 3)

In [11]:
a3.shape

(2, 3, 4)

c) Write code which prints out the following numbers in array `a2`:
> 1. 8
2. 3
3. 12
4. 16

In [12]:
a2=np.array([8,3,12,16])
a2

array([ 8,  3, 12, 16])

d) Write code which prints out the following numbers in array `a3`:
> 1. 3
2. 5
3. 12
4. 16
5. 22
6. 23

In [14]:
a3=np.array([3,5,12,16,22,23])
a3

array([ 3,  5, 12, 16, 22, 23])

e) Change the shape of `a3` to the following shapes:
> 1. (6,4)
2. (2,1,2,3,2)
3. (4,3,2)

In [25]:
a3.reshape((4,3,2))

ValueError: cannot reshape array of size 6 into shape (4,3,2)

In [24]:
a3.reshape((2,1,2,3,2))

ValueError: cannot reshape array of size 6 into shape (2,1,2,3,2)

In [23]:
 a3.reshape((6,4))


ValueError: cannot reshape array of size 6 into shape (6,4)

# Question 2

a) Create a 2 by 2 array with elements generated at random from a normal distribution `N(20,2)`. Store the array on a variable called `a`

In [31]:

a=np.random.normal(20,2,size=(2,2))
a





array([[19.52412851, 18.28941212],
       [17.95501172, 19.5539437 ]])

b) Create a 2 by 2 array with elements generated at random from a uniform distibution `U(37,40)`. Store the array on a variable named `b`

In [32]:
b=np.random.uniform(37,40,size=(2,2))
b

array([[37.15903186, 37.37684043],
       [38.81804878, 39.05063606]])

c) Perfom element wise multiplication of the two arrays and store the answer on a variable named `element_wise_prod`.

In [33]:
element_wise_prod=a*b
element_wise_prod

array([[725.49771332, 683.60043841],
       [696.97852055, 763.59393874]])

d) Perfom matrix multiplication and store the results on a variable called `matrix_multiplication`.

In [34]:
matrix_multiplication = a@b
matrix_multiplication

array([[1435.45700508, 1443.96341229],
       [1426.23679251, 1434.69554658]])

e) Find the maximum number in element_wise_prod and matrix_multiplication

In [35]:
element_wise_prod.max()

763.5939387360736

In [36]:
matrix_multiplication.max()

1443.9634122900288

f) Find the index positions of the answers you obtained in the question above

In [41]:
element_wise_prod[1,1]

763.5939387360736

In [42]:
matrix_multiplication[0,1]

1443.9634122900288

h) Find the mean, max, min and median of the elements in element_wise_prod and matrix_multiplication

In [45]:
element_wise_prod.mean()

717.4176527528567

In [46]:
matrix_multiplication.mean()

1435.0881891151455

In [47]:
element_wise_prod.max()

763.5939387360736

In [48]:
matrix_multiplication.max()

1443.9634122900288

In [50]:
element_wise_prod.min()

683.600438406102

In [51]:
matrix_multiplication.min()

1426.2367925058095

In [107]:
element_wise=np.median(element_wise_prod)
element_wise

711.2381169346256

In [108]:
matrix_multiplication=np.median(matrix_multiplication)
matrix_multiplication

1435.0881891151453

i) Find the mean, max, min and median along the first axis and second axis of element_wise and matrix_multiplication

In [56]:
element_wise_prod.mean(axis=0)

array([711.23811693, 723.59718857])

In [54]:
element_wise_prod.mean(axis=1)

array([704.54907586, 730.28622964])

In [53]:
matrix_multiplication.mean(axis=0)

array([1430.84689879, 1439.32947944])

In [ ]:
matrix_multiplication.mean(axis=1)

array([1430.84689879, 1439.32947944])

In [59]:
element_wise_prod.max(axis=0)

array([725.49771332, 763.59393874])

In [60]:
matrix_multiplication.max(axis=0)

array([1435.45700508, 1443.96341229])

In [61]:
element_wise_prod.max(axis=1)

array([725.49771332, 763.59393874])

In [62]:
matrix_multiplication.max(axis=1)

array([1443.96341229, 1434.69554658])

In [63]:
element_wise_prod.min(axis=0)

array([696.97852055, 683.60043841])

In [64]:
matrix_multiplication.min(axis=0)

array([1426.23679251, 1434.69554658])

In [65]:
element_wise_prod.min(axis=1)

array([683.60043841, 696.97852055])

In [66]:
matrix_multiplication.min(axis=1)

array([1435.45700508, 1426.23679251])

In [101]:
element_wise=np.median(element_wise_prod,axis=0)
element_wise_prod


array([[725.49771332, 683.60043841],
       [696.97852055, 763.59393874]])

In [97]:
element_wise = np.median(element_wise_prod,axis=1)
element_wise

array([704.54907586, 730.28622964])

In [98]:
matrix_multiplication=np.median(matrix_multiplication,axis=0)
matrix_multiplication

array([1430.84689879, 1439.32947944])

In [109]:
matrix_multiplication=np.median(matrix_multiplication,axis=1)
matrix_multiplication

AxisError: axis 1 is out of bounds for array of dimension 0

j) Join the two arrays on the vertical and horizontal axis and store the results on variables called `horizontal_join` and `vertical_join`

In [72]:
horizontal_join=np.hstack((a,b))
horizontal_join

array([[19.52412851, 18.28941212, 37.15903186, 37.37684043],
       [17.95501172, 19.5539437 , 38.81804878, 39.05063606]])

In [73]:
vertical_join=np.vstack((a,b))
vertical_join

array([[19.52412851, 18.28941212],
       [17.95501172, 19.5539437 ],
       [37.15903186, 37.37684043],
       [38.81804878, 39.05063606]])

# Question 3

In [74]:
a = np.random.random(size = (5,4))
b = np.random.exponential(0.4,size=(4,6))
c = a @ b

a) Run the code cell above and check the shape of the result `c`

In [75]:
c.shape

(5, 6)

b) Find all the elements less than 0.5

In [111]:
elements_less_than = c [c<0.5]
elements_less_than

array([0.28919606, 0.23079715, 0.29373055, 0.14668048, 0.40645551,
       0.37382828, 0.39891403, 0.46282878, 0.46712889, 0.32979093])

c) Convert array `c` to a one dimensional array and save the result on variable `d`

In [81]:
d=c.flatten()
d

array([0.28919606, 0.23079715, 0.29373055, 0.14668048, 0.40645551,
       0.37382828, 0.71519683, 0.61139844, 0.75295085, 0.39891403,
       1.05116425, 1.00828756, 0.91999385, 0.64382593, 1.11049089,
       0.56394734, 1.4482395 , 1.13402777, 0.67617483, 0.68124377,
       0.80936298, 0.46282878, 1.038035  , 1.07740018, 0.50387585,
       0.46712889, 0.68332557, 0.32979093, 0.6268232 , 0.56113642])

d) Find the index position with the maximum value in `d`

In [86]:
d[[16]]

array([1.4482395])

# Question 4

a) Create an array of 20 evenly spaced numbers between 17 and 35 and store the results on a variable named `e`

In [89]:
e=np.linspace(17,35,20)
e


array([17.        , 17.94736842, 18.89473684, 19.84210526, 20.78947368,
       21.73684211, 22.68421053, 23.63157895, 24.57894737, 25.52631579,
       26.47368421, 27.42105263, 28.36842105, 29.31578947, 30.26315789,
       31.21052632, 32.15789474, 33.10526316, 34.05263158, 35.        ])

b) Create an array consisting of a sequence of numbers between 17 and 35 with a step of 3 and store the results on a variable named `f`

In [90]:
f=np.arange(17,35,3)
f

array([17, 20, 23, 26, 29, 32])

c) Add a new dimension to `e`. The new dimension should be added as the last dimension of the array `e`. Save the results on a variable named `g`

In [92]:
g=e[:,np.newaxis]
g

array([[17.        ],
       [17.94736842],
       [18.89473684],
       [19.84210526],
       [20.78947368],
       [21.73684211],
       [22.68421053],
       [23.63157895],
       [24.57894737],
       [25.52631579],
       [26.47368421],
       [27.42105263],
       [28.36842105],
       [29.31578947],
       [30.26315789],
       [31.21052632],
       [32.15789474],
       [33.10526316],
       [34.05263158],
       [35.        ]])

d) Add a new dimension to `f`. The dimension should be added as the first dimension to array `f`. Save the results to a variable named `h`

In [93]:
f=np.arange(17,35,3)
h=f[np.newaxis:,]
h

array([17, 20, 23, 26, 29, 32])

e) Remove all the axes of length one in `e` and `f`

In [94]:
e=np.squeeze(e)
e

array([17.        , 17.94736842, 18.89473684, 19.84210526, 20.78947368,
       21.73684211, 22.68421053, 23.63157895, 24.57894737, 25.52631579,
       26.47368421, 27.42105263, 28.36842105, 29.31578947, 30.26315789,
       31.21052632, 32.15789474, 33.10526316, 34.05263158, 35.        ])

In [112]:
f=np.squeeze(f)
f

array([17, 20, 23, 26, 29, 32])